#cloud-config
users:
  - name: %{USER}
    groups: users, admin, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - %{PUBLIC_KEY}
packages:
  - fail2ban
  - ufw
  - wget
  - memcached
  - logrotate
package_update: true
package_upgrade: true
runcmd:
  # General server setup
  - timedatectl set-timezone UTC
  # Fail2Ban setup
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  # UFW and SSH setup
  - ufw allow 22/tcp
  - ufw allow 11211/tcp
  - ufw enable
  # Harden SSH
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers %{USER}' /etc/ssh/sshd_config
  # Set up memcached
  - sed -i 's/-m 64/-m 512/g' /etc/memcached.conf
  - sed -i 's/-l 127.0.0.1/-l 0.0.0.0/g' /etc/memcached.conf
  - systemctl restart memcached.service
  - |
    cat > /etc/logrotate.d/memcached << EOF
    /var/log/redis/memcached*.log {
      daily
      missingok
      rotate 7
      compress
      notifempty
    }
    EOF
  - reboot
