#cloud-config
users:
  - name: %{USER}
    groups: users, admin, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - %{PUBLIC_KEY}
packages:
  - fail2ban
  - ufw
  - wget
  - logrotate
package_update: true
package_upgrade: true
runcmd:
  # General server setup
  - timedatectl set-timezone UTC
  - echo "${USER}:${USER}" | chpasswd
  # Fail2Ban setup
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  # UFW and SSH setup
  - ufw allow 22/tcp
  - ufw allow 6379/tcp
  - ufw enable
  # Harden SSH
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers %{USER}' /etc/ssh/sshd_config
  # Set up Redis
  - apt-get -y install redis-server
  - sed -i 's/supervised no/supervised systemd/g' /etc/redis/redis.conf
  - sed -i 's/bind 127.0.0.1 ::1/# bind 127.0.0.1 ::1/g' /etc/redis/redis.conf
  - sed -i 's/protected-mode yes/protected-mode no/g' /etc/redis/redis.conf
  - systemctl restart redis.service
  - |
    cat > /etc/logrotate.d/redis-server << EOF
    /var/log/redis/redis-server*.log {
      daily
      missingok
      rotate 7
      compress
      notifempty
    }
    EOF
  - reboot
